name: Basic Docker Workflow

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          file: basic.Dockerfile
          target: runtime
          push: false
